name: mx_request
description: 使用dio進行發送自動生成的request請求, 搭配mx_request_generator使用.
version: 1.0.5
homepage: https://github.com/MagicalWater/mx_request

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

