name: mx_http
description: http connection tool, and supporting automatic generation of request entity code.
version: 0.0.2+1
homepage: https://github.com/MagicalWater/mx_http

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  path: ^1.8.0
  source_gen: ^1.2.5
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  analyzer: ^4.7.0
  build: ^2.3.1
  dart_style: ^2.2.4
  code_builder: ^4.1.0
  build_runner: ^2.2.1
  built_collection: ^5.1.1
  meta: ^1.8.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
