name: mx_request
description: 可自動化生成request請求內容的工具, 核心為使用dio進行發送自動生成的request請求.
version: 1.0.0
homepage: https://github.com/MagicalWater/mx_request

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  source_gen: ^1.5.0
  meta: ^1.16.0
  analyzer: ^6.5.2
  dart_style: ^2.3.7
  code_builder: ^4.10.0
  built_collection: ^5.1.1
  build: ^2.4.1
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  build_runner: ^2.4.13

